import test from 'node:test';
import assert from 'node:assert/strict';
import engine from '../lib/engine.js';
import email from '../lib/email.js';
import handler,{validate,validateAttachment} from '../netlify/functions/quote.mjs';
const id='11111111-1111-4111-8111-111111111111';
const productionContext={deploy:{context:'production'}};
function item(productId='brochures',choices={}){const r=engine.resolve(productId,choices);for(const f of r.fields)if(!f.options&&f.required&&!r.state[f.label])r.state[f.label]=f.type==='integer'?String(f.min||8):f.type==='dimension'?'2':'Sample project';return {id:'test-item',productId,choices:r.state,quantity:Number(r.quantities[0]||250),quantityCustom:!r.quantities.length,note:'',buying:false,supplier:'',currentPrice:'',buyingDetails:''};}
function quote(){return {submissionId:id,contact:{company:'Sample Company',contact:'Test Person',email:'person@example.com',phone:'8185550123',recipient:'Test Person',address1:'123 Example St',address2:'',city:'Los Angeles',state:'CA',postal:'90001',country:'United States',promoCode:'',deliveryDate:'',notes:''},items:[item()]};}
function request(q=quote(),origin='https://quixprint.com',file){const form=new FormData();form.set('payload',JSON.stringify(q));if(file)form.set('attachment',file,'artwork.pdf');return new Request('https://quixprint.com/api/quote',{method:'POST',headers:{origin},body:form});}
test('catalog consolidates 33 entries into 30 configurable product pages',()=>{assert.equal(engine.catalog.categories.reduce((n,c)=>n+c.links.length,0),33);assert.equal(engine.catalog.products.length,31);});
test('legacy size and stock dependencies resolve and stale combinations are rejected',()=>{const a=engine.resolve('retractable-banners');const narrow=engine.resolve('retractable-banners',{...a.state,Size:'24" x 81" (Narrow)','Print sides':'Front and Back'});assert.equal(narrow.state['Print sides'],'Front Only');assert.throws(()=>engine.validateItem({...item('retractable-banners'),choices:{...narrow.state,'Print sides':'Front and Back'}}));});
test('flyer mailing reveals and removes dependent mailing fields',()=>{const a=engine.resolve('flyers',{Mailing:'With mailing'});assert.ok('Mailing list' in a.state);assert.ok('Mailing details' in a.state);const b=engine.resolve('flyers',{...a.state,Mailing:'Without mailing'});assert.ok(!('Mailing list' in b.state));assert.ok(!('Mailing details' in b.state));});
test('envelope size limits printing and quantities',()=>{const r=engine.resolve('envelopes',{Size:'6" x 9" Vertical Catalog'});assert.deepEqual(r.fields.find(f=>f.label==='Color').options,['Full Color Front (Outside)']);assert.equal(r.quantities[0],'1000');});
test('raised card finishes only appear on verified stock',()=>{const r=engine.resolve('business-cards',{Paper:'14 pt. Uncoated Cover','Specialty finish':'Raised Foil','Foil color':'Gold'});assert.equal(r.state['Specialty finish'],'None');assert.ok(!('Foil color' in r.state));assert.throws(()=>engine.validateItem({...item('business-cards'),choices:{...r.state,'Specialty finish':'Raised Foil'}}));});
test('booklet binding and small-run constraints reject incompatible choices',()=>{const q=item('booklets-catalogs',{Binding:'Perfect Binding','Page count including cover':'16'});assert.throws(()=>engine.validateItem(q),/48 pages/);assert.throws(()=>engine.validateItem({...item('booklets-catalogs',{Binding:'Perfect Binding','Page count including cover':'64'}),quantity:25}),/25 or 50/);});
test('quantity, hidden specs and current price are validated server-side',()=>{assert.throws(()=>engine.validateItem({...item(),quantity:0}));assert.throws(()=>engine.validateItem({...item(),choices:{...item().choices,Unverified:'yes'}}));assert.throws(()=>engine.validateItem({...item(),buying:true,currentPrice:'-10'}));assert.equal(engine.validateItem({...item(),buying:false,supplier:'ignore',currentPrice:'10'}).supplier,'');});
test('artwork accepts signatures and rejects extension spoofing and oversized data',()=>{assert.equal(validateAttachment('proof.pdf',Buffer.from('%PDF-1.7\n')),'proof.pdf');assert.throws(()=>validateAttachment('proof.pdf',Buffer.from('<html>bad</html>')));assert.throws(()=>validateAttachment('proof.pdf',Buffer.alloc(3000001)));});
test('email content escapes submitted markup and separates purchasing notes',()=>{const q=validate(quote());q.contact.company='<img src=x onerror=alert(1)>';q.items[0].buying=true;q.items[0].supplier='Vendor Secret';const team=email.render(q,'TEST','proof.pdf'),customer=email.render(q,'TEST','proof.pdf',true);assert.ok(!team.html.includes('<img'));assert.ok(team.html.includes('&lt;img'));assert.ok(team.text.includes('Vendor Secret'));assert.ok(!customer.text.includes('Vendor Secret'));assert.ok(customer.text.includes('not an order'));});
test('preview validates without ever contacting an email service',async()=>{const original=globalThis.fetch;globalThis.fetch=()=>{throw new Error('Unexpected network call')};const old={...process.env};try{process.env.SITE_MODE='preview';process.env.QUOTE_MODE='live';process.env.CONTEXT='production';const res=await handler(request(),productionContext);assert.equal(res.status,200);assert.equal((await res.json()).preview,true);}finally{globalThis.fetch=original;process.env=old;}});
test('origin and payload validation prevent direct tampering',async()=>{assert.equal((await handler(request(quote(),'https://evil.example'))).status,403);const q=quote();q.items[0].choices.Paper='Not a real stock';assert.equal((await handler(request(q))).status,400);});
test('live handler sends distinct team and customer emails, attachment only to team',async()=>{const original=globalThis.fetch,old={...process.env},sent=[];try{Object.assign(process.env,{SITE_MODE:'live',QUOTE_MODE:'live',BREVO_API_KEY:'TEST-NOT-A-REAL-KEY',QUOTE_FROM:'sales@quixprint.com'});delete process.env.CONTEXT;globalThis.fetch=async(u,o)=>{sent.push(JSON.parse(o.body));return Response.json({messageId:'test-'+sent.length},{status:201});};const res=await handler(request(quote(),'https://quixprint.com',new Blob(['%PDF-1.7\n'],{type:'application/pdf'})),productionContext);assert.equal(res.status,200);assert.equal((await res.json()).confirmationSent,true);assert.equal(sent.length,2);assert.equal(sent[0].to[0].email,'sales@quixprint.com');assert.equal(sent[1].to[0].email,'person@example.com');assert.ok(sent[0].attachment);assert.ok(!sent[1].attachment);assert.notEqual(sent[0].headers.idempotencyKey,sent[1].headers.idempotencyKey);}finally{globalThis.fetch=original;process.env=old;}});
test('confirmation failure does not lose an accepted sales request',async()=>{const original=globalThis.fetch,old={...process.env};let n=0;try{Object.assign(process.env,{SITE_MODE:'live',QUOTE_MODE:'live',BREVO_API_KEY:'TEST',QUOTE_FROM:'sales@quixprint.com'});delete process.env.CONTEXT;globalThis.fetch=async()=>++n===1?Response.json({messageId:'test'},{status:201}):Response.json({code:'error'},{status:503});const res=await handler(request(),productionContext);const body=await res.json();assert.equal(res.status,200);assert.equal(body.ok,true);assert.equal(body.confirmationSent,false);}finally{globalThis.fetch=original;process.env=old;}});
test('sales delivery failure preserves a retriable request and skips confirmation',async()=>{const original=globalThis.fetch,old={...process.env};let n=0;try{Object.assign(process.env,{SITE_MODE:'live',QUOTE_MODE:'live',BREVO_API_KEY:'TEST',QUOTE_FROM:'sales@quixprint.com'});delete process.env.CONTEXT;globalThis.fetch=async()=>{n++;return Response.json({code:'error'},{status:503});};assert.equal((await handler(request(),productionContext)).status,502);assert.equal(n,1);}finally{globalThis.fetch=original;process.env=old;}});
test('sticker formats remove inactive options and reject stale fields',()=>{const sheet=engine.resolve('stickers',{Format:'Kiss-Cut Sticker Sheets',Size:'Custom size','Width (in)':'8','Height (in)':'5',Material:'White Bopp'});assert.equal(sheet.state.Finishing,'Gloss Lamination');assert.ok('Width (in)' in sheet.state);const individual=engine.resolve('stickers',{...sheet.state,Format:'Individual Stickers',Size:'3 x 2 in'});assert.equal(individual.state.Shape,'Rectangle');assert.equal(individual.state.Material,'White Matte Vinyl');assert.ok(!('Width (in)' in individual.state));assert.throws(()=>engine.validateItem({...item('stickers'),choices:{...individual.state,'Width (in)':'8'}}),/options changed/);});
test('all product defaults accept a complete preferred specification request',()=>{for(const p of engine.catalog.products)assert.equal(engine.validateItem(item(p.id)).productId,p.id,p.id);});
test('counter mats retain the requested Quixprint offering',()=>{const r=engine.resolve('counter-mats');assert.deepEqual(r.fields.find(f=>f.label==='Size').options,['9 x 14 in','10 x 15 in','11 x 17 in']);assert.equal(r.state.Material,'6 mil white vinyl — hard surface');});
test('gloss coating follows printed sides and clears when paper changes',()=>{for(const [id,both,front,coating] of [['business-cards','Full Color Both Sides','Full Color Front, Blank Back','High gloss UV both sides'],['greeting-cards','Full Color Outside and Inside','Full Color Outside, Blank Inside','High gloss UV outside and inside']]){const a=engine.resolve(id,{Paper:'14 pt. Gloss Cover',Printing:both,'Gloss coating':coating});assert.equal(a.state['Gloss coating'],coating);const b=engine.resolve(id,{...a.state,Printing:front});assert.notEqual(b.state['Gloss coating'],coating);const c=engine.resolve(id,{...b.state,Paper:'14 pt. Uncoated Cover'});assert.ok(!('Gloss coating' in c.state));assert.throws(()=>engine.validateItem({...item(id),choices:{...c.state,'Gloss coating':coating}}));}});
test('magnet center split is limited to verified sizes and shapes',()=>{const a=engine.resolve('car-magnets',{Shape:'Rectangle',Size:'28 x 40 in','Center split':'Split into two panels'});assert.equal(a.state['Center split'],'Split into two panels');for(const change of [{Size:'12 x 18 in'},{Shape:'Circle'}])assert.ok(!('Center split' in engine.resolve('car-magnets',{...a.state,...change}).state));});

test('nonproduction and missing native deployment context never send even with live flags',async()=>{const original=globalThis.fetch,old={...process.env};try{Object.assign(process.env,{SITE_MODE:'live',QUOTE_MODE:'live',CONTEXT:'production'});globalThis.fetch=()=>{throw new Error('Unexpected network call')};for(const context of [{deploy:{context:'deploy-preview'}},{deploy:{context:'branch-deploy'}},undefined]){const res=await handler(request(),context);assert.equal(res.status,200);assert.equal((await res.json()).preview,true);}}finally{globalThis.fetch=original;process.env=old;}});
