import test from 'node:test';
import assert from 'node:assert/strict';
import Q from '../lib/engine.js';
import email from '../lib/email.js';
function make(id='roll-labels',extra={}){const r=Q.resolve(id,{Versions:'2',...extra});for(const f of r.fields)if(!f.options&&f.required&&!r.state[f.label])r.state[f.label]=f.type==='integer'?'8':f.type==='dimension'?'2':'Example';return {id:'versions-test',productId:id,choices:r.state,quantity:1250,quantityMode:'breakdown',artworkVersions:[{name:'First design',quantity:500},{name:'Second design',quantity:750}],note:'',buying:false};}
test('unequal artwork quantities are summed once and survive validation',()=>{const v=Q.validateItem(make());assert.equal(v.quantity,1250);assert.equal(v.quantityUnit,'labels');assert.equal(v.artworkVersions[1].quantity,750);assert.equal(v.artworkVersions[1].name,'Second design');assert.deepEqual(Q.validateItem(v),v);});
test('quantity breakdown rejects mismatched totals, missing rows, bad quantities and long names',()=>{const a=make();assert.throws(()=>Q.validateItem({...a,quantity:2500}),/total quantity/);assert.throws(()=>Q.validateItem({...a,artworkVersions:[a.artworkVersions[0]]}),/breakdown/);assert.throws(()=>Q.validateItem({...a,artworkVersions:[{name:'',quantity:-1},a.artworkVersions[1]]}),/Version 1/);assert.throws(()=>Q.validateItem({...a,artworkVersions:[{name:'x'.repeat(101),quantity:500},a.artworkVersions[1]]}),/long/);});
test('legacy carts and notepad quantities keep their previous per-version meaning',()=>{const a=make('notepads');delete a.quantityMode;delete a.artworkVersions;const v=Q.validateItem({...a,quantityCustom:true});assert.equal(v.quantityMode,'per-version');assert.equal(v.quantity,1250);assert.equal(v.quantityUnit,'pads');assert.throws(()=>Q.validateItem(make('notepads')),/breakdown/);});
test('roll labels resolve material and shape dependencies without stale fields',()=>{let r=Q.resolve('roll-labels',{Shape:'Rectangle',Material:'Clear Gloss BOPP','Foil option':'Raised Foil (20 micron)','Foil color':'Gold (shiny)'});assert.equal(r.state.Liner,'Clear 1.2Mil PET Liner');assert.equal(r.state['Print color'],'Full Color + White (5/0)');for(const label of ['Foil option','Foil color','Raised spot UV','Round corners'])assert.ok(!(label in r.state));r=Q.resolve('roll-labels',{...r.state,Shape:'Circle',Material:'Kraft Paper','Foil option':'No'});assert.equal(r.state.Lamination,'No');assert.ok(!('Round corners' in r.state));assert.ok(!('Foil color' in r.state));assert.ok(!('Orientation' in r.state));});
test('custom dimensions require numbers and paired width and height',()=>{const a=make('roll-labels',{Size:'Custom size','Width (in)':'3','Height (in)':'4'});assert.equal(Q.validateItem(a).choices['Height (in)'],'4');assert.throws(()=>Q.validateItem({...a,choices:{...a.choices,'Height (in)':''}}),/Height/);assert.throws(()=>Q.validateItem(make('roll-labels',{Shape:'Circle',Size:'Custom size','Width (in)':'3','Height (in)':'4'})),/matching width and height/);});
test('customer and team emails show version names and unequal quantities without multiplying totals',()=>{const item=Q.validateItem(make());item.artworkVersions[0].name='<script>Design</script>';const quote={contact:{company:'Example',contact:'Test',email:'test@example.com',phone:'5555555555',recipient:'Test',address1:'1 Main',city:'LA',state:'CA',postal:'90001',country:'US'},items:[item]};for(const customer of [true,false]){const e=email.render(quote,'PREVIEW','',customer);assert.match(e.text,/Total quantity: 1,250 labels/);assert.match(e.text,/Version 2 — Second design: 750 labels/);assert.ok(!e.text.includes('2,500'));assert.ok(!e.html.includes('<script>Design'));assert.ok(e.html.includes('&lt;script&gt;Design'));}});

test('every eligible product accepts independent artwork quantities',()=>{for(const p of Q.catalog.products.filter(p=>p.versionMode==='breakdown')){const a=make(p.id);assert.equal(Q.validateItem(a).quantity,1250,p.id);}});
test('sticker material changes clear incompatible finishes and use format-specific units',()=>{const a=Q.resolve('stickers',{Format:'Kiss-Cut Stickers',Material:'Holographic Vinyl',Finishing:'Gloss Lamination - 5 Mil Thick'});assert.equal(a.state.Finishing,'Gloss Lamination - 5 Mil Thick');const b=Q.resolve('stickers',{...a.state,Material:'Clear Gloss Vinyl'});assert.ok(!('Finishing' in b.state));assert.equal(b.state['Print color'],'Full Color + White (5/0)');assert.equal(Q.quantityUnit(Q.product('stickers'),{Format:'Kiss-Cut Sticker Sheets'}),'sheets');assert.equal(Q.quantityUnit(Q.product('stickers'),{Format:'Sticker Sheets'}),'stickers');});
