(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.QXP_EMAIL=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(quote,reference,filename,customer=false){
 const c=quote.contact,title=customer?'Your quote request is in.':'New printing quote request';
 const intro=customer?'Thanks for thinking of Quixprint. We’ll review your specifications and respond with pricing. This confirms receipt of a quote request, not an order.':'Review the requested specifications, quantities, and delivery details before providing pricing.';
 const sections=[['Request',[`Reference: ${reference}`,`Company: ${c.company}`,`Contact: ${c.contact}`,`Email: ${c.email}`,`Phone: ${c.phone}`]],['Shipping',[c.recipient,c.address1,c.address2,`${c.city}, ${c.state} ${c.postal}`,c.country].filter(Boolean)]];
 quote.items.forEach((item,i)=>{const versions=Number(item.choices.Versions||1),unit=item.quantityUnit||(item.productId==='notepads'?'pads':item.productId==='roll-labels'?'labels':item.productId==='stickers'&&/Sheets/.test(item.choices.Format||'')?'sheets':'pieces'),split=item.quantityMode==='breakdown';
 const rows=[`${split?'Total quantity':'Quantity'}: ${item.quantity.toLocaleString('en-US')} ${unit}${!split&&versions>1?' per artwork version':''}`,...Object.entries(item.choices).filter(([k,v])=>v&&!(k==='Versions'&&v==='1')).map(([k,v])=>`${k}: ${v}`)];
 if(split&&item.artworkVersions?.length>1)item.artworkVersions.forEach((v,j)=>rows.push(`Version ${j+1}${v.name?' — '+v.name:''}: ${v.quantity.toLocaleString('en-US')} ${unit}`));
 if(!split&&versions>1)rows.push(`Total quantity: ${(item.quantity*versions).toLocaleString('en-US')} ${unit}`);
 if(item.note)rows.push(`Notes: ${item.note}`);if(!customer&&item.buying){rows.push('Already buying: Yes');if(item.supplier)rows.push('Supplier: '+item.supplier);if(item.currentPrice!=='')rows.push('Current price: $'+item.currentPrice+' USD including shipping and tax');if(item.buyingDetails)rows.push('Purchasing details: '+item.buyingDetails);}if(!customer&&item.reviewRequired)rows.push('Review: check requested specifications before quoting.');sections.push([`${i+1}. ${item.product}`,rows]);});
 sections.push(['Project details',[`Artwork: ${filename||'To follow'}`,...(c.deliveryDate?[`Requested delivery date: ${c.deliveryDate}`]:[]),...(c.promoCode?[`Promotional code: ${c.promoCode}`]:[]),...(c.notes?[`Notes: ${c.notes}`]:[])]]);
 const text=[title,intro,...sections.map(([h,lines])=>h+'\n'+lines.join('\n')),'Quixprint · sales@quixprint.com','The proof is in the printing.'].join('\n\n');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title></head><body style="margin:0;background:#f4f5f7;color:#111b2c;font-family:Arial,Helvetica,sans-serif;padding:30px 18px"><main style="max-width:620px;margin:auto;background:white;padding:35px"><p style="font-size:15px;font-weight:bold;color:#1455ee;letter-spacing:1px;margin-top:0">QUIXPRINT</p><h1 style="font-size:32px;line-height:1.1;letter-spacing:-1px;font-weight:500;margin:30px 0 18px">${esc(title)}</h1><p style="font-size:14px;line-height:1.7;color:#5c6573">${esc(intro)}</p><p style="font-size:12px;letter-spacing:1px;color:#1455ee">${esc(reference)}</p>${sections.map(([h,lines])=>`<section style="padding:22px 0;border-top:1px solid #dfe3e9"><h2 style="font-size:17px;font-weight:600;margin:0 0 12px">${esc(h)}</h2><div style="font-size:13px;line-height:1.85;overflow-wrap:anywhere">${lines.map(l=>esc(l).replace(/\n/g,'<br>')).join('<br>')}</div></section>`).join('')}<p style="font-size:12px;line-height:1.7;color:#5c6573">Questions or a change to your request? Reply to this email.<br><a href="mailto:sales@quixprint.com" style="color:#1455ee">sales@quixprint.com</a></p><p style="font-size:13px;border-top:1px solid #dfe3e9;padding-top:20px">The proof is in the printing.</p></main></body></html>`;
 return {html,text};
}
return {render};
});
