import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
const revision=process.argv[2]||'05';
const out=path.resolve(root,'../deliverables');
fs.mkdirSync(out,{recursive:true});
let full=fs.readFileSync(path.join(root,'Quixprint-Full-Preview.html'),'utf8').replace('WEBSITE PREVIEW <span>','WEBSITE PREVIEW · REVISION '+revision+' <span>');
for(const m of full.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
fs.writeFileSync(path.join(out,'Quixprint-Website-Revision-'+revision+'.html'),full);
const initial=[...full.matchAll(/<script>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('window.QXP_PAGES='));
const context={window:{},document:{querySelectorAll:()=>[]}};vm.runInNewContext(initial[1],context);
const w=context.window;w.QXP_PAGES={'/':w.QXP_PAGES['/']};
for(const p of w.QXP_CATALOG.products)p.image='';
const used=new Set([...w.QXP_PAGES['/'].html.matchAll(/data-qxp-src="([^"]+)"/g)].map(m=>m[1]));used.add('/assets/quixprint-logo.png');for(const key of Object.keys(w.QXP_ASSETS))if(!used.has(key))delete w.QXP_ASSETS[key];
const boot=Object.entries(w).map(([k,v])=>'window.'+k+'='+(typeof v==='function'?v.toString():JSON.stringify(v).replaceAll('<','\\u003c'))+';').join('')+'window.QXP_HYDRATE(document);';
let home=full.replace(initial[0],()=>'<script>'+boot+'</script>').replace('WEBSITE PREVIEW · REVISION','HOMEPAGE PREVIEW · REVISION').replace('Explore the design. Quote requests aren’t sent.','Homepage design preview.');
const guard=`<script>document.addEventListener('click',function(e){const a=e.target.closest('a');if(!a)return;const href=a.getAttribute('href')||'';if(href.startsWith('/')&&new URL(href,'https://preview.quixprint.invalid').pathname!=='/'){e.preventDefault();e.stopImmediatePropagation();const el=document.getElementById('toast');el.textContent='This smaller preview includes the homepage only. Use the full website preview to explore other pages.';el.hidden=false;setTimeout(()=>el.hidden=true,5000);}},true);</script>`;
const end=home.lastIndexOf('</body>');home=home.slice(0,end)+guard+home.slice(end);
for(const m of home.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
fs.writeFileSync(path.join(out,'Quixprint-Homepage-Revision-'+revision+'.html'),home);
console.log(JSON.stringify({revision,fullBytes:Buffer.byteLength(full),homepageBytes:Buffer.byteLength(home)}));
