(function(){
'use strict';
const Q=window.QXP,C=window.QXP_CONFIG||{preview:true},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>window.QXP_ICONS?.[name]||'';
const STORE=window.QXP_OFFLINE?'qxp.preview.quote.v1':'qxp.quote.v1',RECEIPT=window.QXP_OFFLINE?'qxp.preview.receipt.v1':'qxp.receipt.v1';let memoryCart=[],memoryReceipt=null,menuTimer,toastTimer,storageWarned=false,storageAvailable=true;
const uid=()=>{if(crypto.randomUUID)return crypto.randomUUID();return '10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16));};
const route=()=>new URL(window.QXP_OFFLINE?(location.hash.slice(1)||'/'):location.href,'https://preview.quixprint.invalid');
const productURL=p=>p.id==='custom-printing'?'/custom-printing/':'/products/'+p.id+'/';
function warning(){if(storageWarned)return;storageWarned=true;const n=document.createElement('div');n.className='storage-warning';n.textContent='Browser storage is unavailable. Your selections may not survive a page refresh.';document.body.prepend(n);}
function cart(){if(!storageAvailable)return memoryCart;try{const raw=JSON.parse(localStorage.getItem(STORE)||'null');if(raw&&Date.now()-raw.updated<30*24*60*60*1000&&Array.isArray(raw.items)){memoryCart=raw.items.filter(x=>x&&typeof x==='object').slice(0,30);}else{memoryCart=[];if(raw)localStorage.removeItem(STORE);}}catch{storageAvailable=false;warning()}return memoryCart;}
function saveCart(items){memoryCart=items;try{if(storageAvailable)localStorage.setItem(STORE,JSON.stringify({updated:Date.now(),items}));}catch{storageAvailable=false;warning()}updateCount();}
function updateCount(){$$('[data-cart-count]').forEach(el=>el.textContent=cart().length);}
function toast(message){const el=$('#toast');if(!el)return;clearTimeout(toastTimer);el.textContent=message;el.hidden=false;toastTimer=setTimeout(()=>el.hidden=true,4500);}
function menu(open){clearTimeout(menuTimer);const m=$('#product-menu'),t=$('#products-toggle');if(!m||!t)return;m.hidden=!open;t.setAttribute('aria-expanded',String(open));$('#menu-scrim').hidden=!open;}
function bindUnwindGuide(){const dialog=$('#unwind-guide');if(!dialog)return;dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)$('#unwind-guide').close();});}
function bindHeader(){const t=$('#products-toggle'),link=$('#products-link'),group=$('.products-nav'),m=$('#product-menu');if(!t||!m||!group)return;t.addEventListener('click',()=>menu(m.hidden));group.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&innerWidth>760)menu(true)});group.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse')menuTimer=setTimeout(()=>menu(false),240)});link.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();menu(true);$('a',m)?.focus();}});m.addEventListener('pointerenter',()=>clearTimeout(menuTimer));m.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse')menuTimer=setTimeout(()=>menu(false),240)});$('#menu-scrim').addEventListener('click',()=>menu(false));$$('.category-toggle').forEach(b=>b.addEventListener('click',()=>{if(innerWidth>760)return;const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));$('#'+b.getAttribute('aria-controls')).classList.toggle('open',open);$('span',b).innerHTML=icon(open?'minus':'plus')}));}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#product-menu')&&!$('#product-menu').hidden){menu(false);$('#products-link').focus()}});
document.addEventListener('focusin',e=>{const m=$('#product-menu');if(m&&!m.hidden&&!m.contains(e.target)&&!$('.products-nav')?.contains(e.target))menu(false)});
document.addEventListener('click',e=>{if(e.target.closest('[data-close-unwind]'))$('#unwind-guide').close();if(e.target.closest('[data-close-dialog]'))$('#added-dialog').close();const a=e.target.closest('a');if(a){menu(false);if($('#added-dialog')?.open)$('#added-dialog').close();}if(!window.QXP_OFFLINE||!a||a.target==='_blank'||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const href=a.getAttribute('href');if(href==='#main'){e.preventDefault();$('#main')?.focus();return;}if(!href||!href.startsWith('/'))return;e.preventDefault();const u=new URL(href,'https://preview.quixprint.invalid');if(window.QXP_PAGES[u.pathname]){const hash='#'+u.pathname+u.search+(u.hash||'');if(location.hash===hash)renderOffline();else location.hash=hash;}else location.href='https://quixprint.com'+href;});
function initCatalog(){const input=$('#product-search');if(!input)return;let selected=route().searchParams.get('category')||'all';function filter(){const query=input.value.trim().toLowerCase();let count=0;$$('[data-catalog-product]').forEach(el=>{const p=Q.product(el.dataset.catalogProduct),text=[p.name,p.category,p.description,p.headline,JSON.stringify(p.config||{}),...(p.tags||[])].join(' ').toLowerCase();const visible=(selected==='all'||p.category===selected)&&text.includes(query);el.hidden=!visible;if(visible)count++});$('#result-count').textContent=count+' products';$('#no-results').hidden=count>0;$$('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===selected)));}if(!Q.catalog.categories.some(c=>c.name===selected))selected='all';$$('[data-category]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.category;filter()}));input.addEventListener('input',filter);filter();}
function specificationRows(choices){return Object.entries(choices||{}).filter(([k,v])=>v&&!(k==='Versions'&&v==='1')).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');}
function unit(p,choices){return Q.quantityUnit(p,choices);}
function quantityText(item,p){const versions=Number(item.choices?.Versions||1),u=unit(p,item.choices);if(item.quantityMode==='breakdown')return Number(item.quantity).toLocaleString()+' '+u+' total'+(versions>1?' · '+versions+' artwork versions':'');return Number(item.quantity).toLocaleString()+' '+u+(versions>1?' per version · '+versions+' versions · '+(item.quantity*versions).toLocaleString()+' total':'');}
function versionsHTML(item){return item.quantityMode==='breakdown'&&item.artworkVersions?.length>1?'<div class="version-summary">'+item.artworkVersions.map((v,i)=>'<p><strong>Version '+(i+1)+(v.name?' · '+esc(v.name):'')+'</strong> — '+Number(v.quantity).toLocaleString()+' '+esc(item.quantityUnit||'pieces')+'</p>').join('')+'</div>':'';}
function error(el,message){el.textContent=message;el.hidden=!message;if(message){el.tabIndex=-1;el.focus();}}
function initProduct(){
 const form=$('#product-form');if(!form)return;
 const p=Q.product(form.dataset.product),params=route().searchParams,editId=params.get('edit'),editing=cart().find(x=>x.id===editId&&x.productId===p.id),split=p.versionMode==='breakdown';
 let choices={...(editing?.choices||{})},quantity=editing?.quantity||'',quantityCustom=editing?.quantityCustom||false,resolved;
 let versionRows=editing?.quantityMode==='breakdown'?editing.artworkVersions.map(v=>({...v})):Array.from({length:Number(choices.Versions||1)},()=>({name:'',quantity:quantity||''}));
 if(editing?.quantityMode==='breakdown'&&versionRows.length===1)quantity=versionRows[0].quantity;
 if(p.id==='stickers'&&params.get('format'))choices={...choices,Format:params.get('format')};
 if(p.customOnly&&params.get('product')&&!editing)choices={'Project description':'I’m interested in '+params.get('product')+'.',...choices};
 if(editing){$('#item-note').value=editing.note||'';$('#already-buying').checked=editing.buying===true;$('#supplier').value=editing.supplier||'';$('#current-price').value=editing.currentPrice||'';$('#buying-notes').value=editing.buyingDetails||'';$('#buying-details').open=!!editing.buying;$('#add-to-quote').innerHTML='Save changes '+icon('arrow-up-right');}
 function choose(f,value){choices[f.label]=value;renderFields(f.label);}
 function renderFields(focusLabel){
  resolved=Q.resolve(p.id,choices);choices=resolved.state;
  const root=$('#config-fields');root.replaceChildren();const grid=document.createElement('div');grid.className='field-grid';
  resolved.fields.filter(f=>f.label!=='Versions').forEach((f,i)=>{
   if(f.options&&f.ui){
    const set=document.createElement('fieldset');set.className='spec-option-field span-full';const legend=document.createElement('legend');legend.textContent=f.label;set.append(legend);
    const buttons=document.createElement('div');buttons.className='spec-options '+(f.ui==='shape'?'shape-options':f.ui==='material'?'material-options':'');
    f.options.forEach(value=>{const button=document.createElement('button');button.type='button';button.dataset.spec=f.label;button.dataset.value=value;button.setAttribute('aria-pressed',String(value===f.value));
     if(['shape','orientation','material'].includes(f.ui)){const icon=document.createElement('span');icon.setAttribute('aria-hidden','true');icon.className=f.ui==='shape'?'shape-icon shape-'+value.toLowerCase().replaceAll(' ','-'):f.ui==='orientation'?'orientation-icon orientation-'+value.toLowerCase():'material-swatch '+(/holographic/i.test(value)?'holographic':/silver/i.test(value)?'silver':/clear/i.test(value)?'clear':/kraft/i.test(value)?'kraft':'');button.append(icon);}
     const caption=document.createElement('span');caption.textContent=value;button.append(caption);button.addEventListener('click',()=>choose(f,value));buttons.append(button);
    });set.append(buttons);if(f.help){const help=document.createElement('p');help.className='field-help';help.textContent=f.help;set.append(help);}grid.append(set);return;
   }
   const label=document.createElement('label');label.className='field'+(f.type==='textarea'?' span-full':'');const text=document.createElement('span');text.textContent=f.label+(f.required?' *':'');label.append(text);let el;
   if(f.options&&f.options.length===1){el=document.createElement('span');el.className='spec-fixed';el.textContent=f.value;}
   else if(f.options){el=document.createElement('select');f.options.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.append(o)});}
   else{el=document.createElement(f.type==='textarea'?'textarea':'input');if(el.tagName==='INPUT')el.type=['integer','dimension','number'].includes(f.type)?'number':'text';if(el.type==='number'){el.min=f.min||'0.01';el.step=f.type==='integer'?'1':'any';if(f.max!=null)el.max=f.max;}if(el.tagName==='TEXTAREA')el.rows=3;el.maxLength=f.maxLength||500;}
   el.id='spec-'+i;el.dataset.spec=f.label;el.value=f.value;el.required=!!f.required;
   el.addEventListener(f.options?'change':'input',()=>{choices[f.label]=el.value;if(f.options)renderFields(f.label)});label.append(el);
   if(f.customSize&&f.value!=='Custom size'){const custom=document.createElement('button');custom.type='button';custom.className='custom-size-button';custom.textContent='Custom size';custom.addEventListener('click',()=>choose(f,'Custom size'));label.append(custom);}
   if(f.guide==='unwind'){const guide=document.createElement('button');guide.type='button';guide.className='custom-size-button';guide.textContent='View roll unwind guide';guide.setAttribute('aria-haspopup','dialog');guide.setAttribute('aria-controls','unwind-guide');guide.addEventListener('click',()=>$('#unwind-guide').showModal());label.append(guide);}if(f.help){const h=document.createElement('span');h.className='field-help';h.textContent=f.help;label.append(h);}grid.append(label);
  });root.append(grid);renderQuantity();if(focusLabel){const focus=$$('[data-spec]').find(el=>el.dataset.spec===focusLabel&&(el.dataset.value===undefined||el.dataset.value===choices[focusLabel]));focus?.focus({preventScroll:true});}
 }
 function count(){return Number(choices.Versions||1);}
 function total(){return versionRows.slice(0,count()).reduce((sum,v)=>sum+(Number(v.quantity)||0),0);}
 function updateTotal(){if(split&&count()>1){quantity=total();const el=$('#quantity-total');if(el)el.value=Number(quantity).toLocaleString();const text=$('#version-total');if(text)text.textContent=Number(quantity).toLocaleString()+' '+Q.quantityUnit(p,choices);}}
 function setVersions(value){choices.Versions=String(value);const n=Number(value);if(!Number.isInteger(n)||n<1||n>10000)return;const base=versionRows[0]?.quantity||quantity||resolved.quantities[0]||'';while(versionRows.length<n)versionRows.push({name:'',quantity:base});if(n===1){quantity=versionRows[0]?.quantity||quantity;quantityCustom=!resolved.quantities.includes(String(quantity));}renderQuantity();}
 function renderQuantity(){
  const root=$('#quantity-fields');root.replaceChildren();const breakdown=$('#version-breakdown');breakdown.replaceChildren();
  const n=count(),many=split&&n>1,qlabel=document.createElement('label');qlabel.className='field';qlabel.textContent=(many?'Total quantity':p.id==='notepads'?'Quantity (pads)':'Quantity')+' *';
  if(many){const input=document.createElement('input');input.id='quantity-total';input.type='text';input.readOnly=true;input.className='quantity-total';input.value=total().toLocaleString();qlabel.append(input);root.append(qlabel);quantity=total();}
  else{
   if(resolved.quantities.length){const s=document.createElement('select');s.id='quantity-select';for(const q of resolved.quantities){const o=document.createElement('option');o.value=q;o.textContent=Number(q).toLocaleString();s.append(o);}const other=document.createElement('option');other.value='custom';other.textContent='Custom quantity';s.append(other);
    if(!quantity)quantity=resolved.quantities[0];if(!quantityCustom&&!resolved.quantities.includes(String(quantity)))quantity=resolved.quantities[0];s.value=quantityCustom?'custom':String(quantity);
    s.addEventListener('change',()=>{quantityCustom=s.value==='custom';quantity=quantityCustom?'':s.value;versionRows[0]={...(versionRows[0]||{}),quantity};renderQuantity();$('#custom-quantity')?.focus();});qlabel.append(s);
   }else quantityCustom=true;
   root.append(qlabel);
   if(quantityCustom){const input=document.createElement('input');input.id='custom-quantity';input.type='number';input.min=1;input.max=10000000;input.step=1;input.required=true;input.inputMode='numeric';input.placeholder='Enter quantity';input.value=quantity;input.addEventListener('input',()=>{quantity=input.value;versionRows[0]={...(versionRows[0]||{}),quantity};});
    if(resolved.quantities.length){const label=document.createElement('label');label.className='field';label.textContent='Custom quantity *';label.append(input);root.append(label);}else qlabel.append(input);
   }versionRows[0]={...(versionRows[0]||{name:''}),quantity};
  }
  const label=document.createElement('label');label.className='field';label.textContent='Artwork versions *';const stepper=document.createElement('div');stepper.className='versions-stepper';
  const minus=document.createElement('button');minus.type='button';minus.innerHTML=icon('minus');minus.setAttribute('aria-label','Remove an artwork version');minus.disabled=n<=1;minus.addEventListener('click',()=>setVersions(Math.max(1,n-1)));
  const input=document.createElement('input');input.id='artwork-versions';input.setAttribute('aria-label','Number of artwork versions');input.type='number';input.min=1;input.max=10000;input.step=1;input.value=choices.Versions||'1';input.required=true;input.addEventListener('input',()=>choices.Versions=input.value);input.addEventListener('change',()=>setVersions(input.value));
  const plus=document.createElement('button');plus.type='button';plus.innerHTML=icon('plus');plus.setAttribute('aria-label','Add an artwork version');plus.disabled=n>=10000;plus.addEventListener('click',()=>setVersions(n+1));stepper.append(minus,input,plus);label.append(stepper);root.append(label);
  if(many&&Number.isInteger(n)&&n<=10000){
   const box=document.createElement('div');box.className='version-breakdown';const heading=document.createElement('div');heading.className='version-breakdown-heading';heading.textContent='Your artwork breakdown';box.append(heading);
   for(let i=0;i<n;i++){
    const v=versionRows[i]||(versionRows[i]={name:'',quantity:versionRows[0]?.quantity||''}),row=document.createElement('div');row.className='version-row';const title=document.createElement('span');title.className='version-name';title.textContent='Version '+(i+1);row.append(title);
    const nameLabel=document.createElement('label');nameLabel.className='field';const nt=document.createElement('span');nt.textContent='Name (optional)';const name=document.createElement('input');name.type='text';name.maxLength=100;name.placeholder='e.g. Design '+(i+1);name.value=v.name||'';name.dataset.versionName=String(i);name.addEventListener('input',()=>v.name=name.value);nameLabel.append(nt,name);
    const qLabel=document.createElement('label');qLabel.className='field';const qt=document.createElement('span');qt.textContent='Quantity';const q=document.createElement('input');q.type='number';q.min=1;q.max=10000000;q.step=1;q.required=true;q.inputMode='numeric';q.value=v.quantity;q.dataset.versionQuantity=String(i);q.addEventListener('input',()=>{v.quantity=q.value;updateTotal();});qLabel.append(qt,q);row.append(nameLabel,qLabel);box.append(row);
   }
   const summary=document.createElement('div');summary.className='version-total';const caption=document.createElement('span');caption.textContent='Total';const value=document.createElement('span');value.id='version-total';value.setAttribute('aria-live','polite');summary.append(caption,value);box.append(summary);breakdown.append(box);updateTotal();
  }
  $('#quantity-help').textContent=p.id==='notepads'?'Quantity is per artwork version. A pad contains the selected number of sheets.':p.id==='custom-printing'?'Quantity is per artwork version.':Q.quantityUnit(p,choices)==='sheets'?'Quantity counts printed sheets.':p.id==='roll-labels'?'Quantity counts individual labels.':p.id==='stickers'&&choices.Format==='Sticker Sheets'?'Quantity counts individual stickers, supplied on sheets.':'';
 }
 function syncBuyingFields(){const active=$('#already-buying').checked;$('#buying-fields').hidden=!active;$$('input,textarea',$('#buying-fields')).forEach(el=>el.disabled=!active);}syncBuyingFields();$('#already-buying').addEventListener('change',syncBuyingFields);
 form.addEventListener('submit',e=>{e.preventDefault();error($('#product-error'),'');try{
  const n=count();if(split&&Number.isInteger(n)&&n>1)quantity=total();
  const item=Q.validateItem({id:editing?.id||uid(),productId:p.id,choices,quantity,quantityCustom,...(split?{quantityMode:'breakdown',artworkVersions:versionRows.slice(0,n)}:{}),note:$('#item-note').value,buying:$('#already-buying').checked,supplier:$('#supplier').value,currentPrice:$('#current-price').value,buyingDetails:$('#buying-notes').value});let items=cart();if(editing)items=items.map(x=>x.id===item.id?item:x);else{if(items.length>=30)throw new Error('Please submit these 30 items before starting another quote.');items=[...items,item];}saveCart(items);$('#added-title').textContent=editing?'Your quote is updated.':'Added to your quote.';$('#added-description').textContent=p.name+' · '+quantityText(item,p);$('#added-dialog').showModal();
 }catch(ex){error($('#product-error'),ex.message);}});renderFields();
}
function buyingHTML(item){return item.buying?`<details class="item-note"><summary>Current purchasing details</summary><p>${item.supplier?'Supplier: '+esc(item.supplier)+'<br>':''}${item.currentPrice!==''?'Current total: $'+esc(item.currentPrice)+' including shipping and tax<br>':''}${esc(item.buyingDetails||'')}</p></details>`:'';}
function initCart(){const root=$('#cart-items');if(!root)return;const items=cart();$('#cart-summary').hidden=!items.length;$('#cart-item-count').textContent=items.length+' item'+(items.length===1?'':'s')+' · Ready for our team to review';if(!items.length){root.innerHTML='<div class="empty-state"><span class="eyebrow">A fresh start</span><h2>What are we printing?</h2><p>Add a product to your quote, or tell us about a custom project.</p><div class="actions"><a class="button" href="/products/">Explore products '+icon('arrow-right')+'</a><a class="text-link" href="/custom-printing/">Request something custom '+icon('arrow-right')+'</a></div></div>';return;}root.innerHTML=items.map(item=>{const p=Q.product(item.productId);if(!p)return `<article class="cart-item"><div></div><div><h2>Product no longer available</h2><button class="text-button" data-remove="${esc(item.id)}">Remove item</button></div></article>`;let invalid='';try{Q.validateItem(item)}catch{invalid='<p class="form-error">Some options have changed. Please edit this item before submitting.</p>';}return `<article class="cart-item"><a href="${productURL(p)}"><img src="${p.image}" alt="${esc(p.name)}" width="125" height="94"></a><div><h2>${esc(p.name)}</h2><p class="quantity">${quantityText(item,p)}</p>${invalid}<dl class="item-specs">${specificationRows(item.choices)}</dl>${versionsHTML(item)}${item.note?'<p class="item-note">'+esc(item.note)+'</p>':''}${buyingHTML(item)}<div class="item-actions"><a class="text-link" href="${productURL(p)}?edit=${encodeURIComponent(item.id)}">Edit specifications</a><button type="button" class="text-button" data-remove="${esc(item.id)}">Remove</button></div></div></article>`}).join('');window.QXP_HYDRATE?.(root);$$('[data-remove]',root).forEach(b=>b.addEventListener('click',()=>{saveCart(cart().filter(x=>x.id!==b.dataset.remove));initCart();toast('Item removed from your quote.')}));}
function summaryHTML(items){return items.map(item=>{const p=Q.product(item.productId);return `<div class="checkout-summary-item"><h3>${esc(p?.name||item.product)}</h3><p>${p?quantityText(item,p):''}</p><details><summary>View specifications</summary><dl class="item-specs">${specificationRows(item.choices)}</dl>${versionsHTML(item)}${item.note?'<p class="item-note">'+esc(item.note)+'</p>':''}${buyingHTML(item)}</details></div>`}).join('');}
function getReceipt(){try{return JSON.parse(sessionStorage.getItem(RECEIPT)||'null')||memoryReceipt}catch{return memoryReceipt}}
function saveReceipt(r){memoryReceipt=r;try{sessionStorage.setItem(RECEIPT,JSON.stringify(r))}catch{warning()}}
function navigate(path){if(window.QXP_OFFLINE){location.hash='#'+path;}else location.href=path;}
function checkFile(file){if(!file)return '';if(file.size>3000000)return 'Please choose a file under 3 MB, or send artwork later by email.';if(!/\.(pdf|jpg|jpeg|png|tif|tiff|zip)$/i.test(file.name))return 'Choose a PDF, JPG, PNG, TIFF, or ZIP file.';return '';}
async function attemptId(contact,items,file,fallback){if(!crypto.subtle)return fallback;const hash=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join('');const fileHash=file?await hash(await file.arrayBuffer()):'';const fingerprint=await hash(new TextEncoder().encode(JSON.stringify({contact,items,file:file?.name||'',fileHash})));let old;try{old=JSON.parse(sessionStorage.getItem('qxp.attempt')||'null')}catch{}if(old?.fingerprint===fingerprint){if(Date.now()-old.created>25*60*1000)throw new Error('An earlier matching request could not be confirmed. Please email sales@quixprint.com with reference QXP-'+old.id.replaceAll('-','').slice(0,12).toUpperCase()+' before submitting again.');return old.id;}const id=uid();try{sessionStorage.setItem('qxp.attempt',JSON.stringify({fingerprint,id,created:Date.now()}))}catch{}return id;}
function initCheckout(){const form=$('#checkout-form');if(!form)return;let items=cart(),submissionId=uid();const button=$('#submit-quote');$('#checkout-items').innerHTML=summaryHTML(items);if(!items.length){button.disabled=true;error($('#checkout-error'),'Your quote is empty. Add a product before submitting.');}else try{items.forEach(Q.validateItem)}catch{button.disabled=true;error($('#checkout-error'),'Some product options have changed. Return to your quote and edit the affected items.');}
 const file=$('#artwork');file.addEventListener('change',()=>{const f=file.files[0];$('#remove-artwork').hidden=!f;$('#artwork-status').textContent=f?(checkFile(f)||f.name+' · '+(f.size/1000000).toFixed(2)+' MB'):'';});$('#remove-artwork').addEventListener('click',()=>{file.value='';$('#remove-artwork').hidden=true;$('#artwork-status').textContent='';});
 form.addEventListener('submit',async e=>{e.preventDefault();error($('#checkout-error'),'');let request;try{items=cart().map(Q.validateItem);if(!items.length)throw new Error('Please add a product first.');const data=new FormData(form),contact=Object.fromEntries(data.entries());delete contact.company_website;if(contact.phone.replace(/\D/g,'').length<7)throw new Error('Please enter a complete phone number.');const f=file.files[0],fileError=checkFile(f);if(fileError)throw new Error(fileError);request={submissionId,contact,items};button.disabled=true;button.textContent=C.preview?'Preparing your preview…':'Sending your request…';let response;
 if(window.QXP_OFFLINE){response={ok:true,preview:true,reference:'PREVIEW-'+submissionId.slice(0,8).toUpperCase(),confirmationSent:false};}
 else{if(!C.preview){submissionId=await attemptId(contact,items,f,submissionId);request.submissionId=submissionId;}const body=new FormData();body.set('payload',JSON.stringify(request));body.set('company_website',data.get('company_website')||'');if(f)body.set('attachment',f);let r;try{r=await fetch('/api/quote',{method:'POST',body,signal:AbortSignal.timeout(55000)});}catch{throw new Error('We couldn’t confirm the request. Your cart is saved. Try again, or contact sales@quixprint.com.');}response=await r.json().catch(()=>null);if(!r.ok||!response?.ok)throw new Error(response?.error||'We couldn’t confirm your request. Your cart is saved. Please try again.');}
 saveReceipt({...response,quote:request,filename:f?.name||'',created:Date.now()});if(!response.preview){saveCart([]);try{sessionStorage.removeItem('qxp.attempt')}catch{}}navigate('/quote/received/');
 }catch(ex){error($('#checkout-error'),ex.message);button.disabled=false;button.innerHTML=(C.preview?'Preview quote request':'Submit quote request')+' '+icon('arrow-right');}});}
function initReceipt(){const root=$('#receipt');if(!root)return;const r=getReceipt();if(!r||Date.now()-r.created>2*60*60*1000)return;const c=r.quote.contact;root.innerHTML=`<div class="page-heading compact"><span class="eyebrow">${r.preview?'Preview complete':'Thank you for thinking of us'}</span><h1>${r.preview?'That’s your quote<br><em>request, ready.</em>':'Your project is<br><em>in good hands.</em>'}</h1><p>${r.preview?'Nothing was sent. Here’s how your request will come together. Your quote cart is still available to edit.':'We’ve received your request and will review the details before sending pricing.'}</p></div><span class="code-reference">${esc(r.reference)}</span><div class="receipt-box"><h2>${esc(c.company)}</h2><div class="receipt-contact">${esc(c.contact)} · ${esc(c.email)}<br>${esc(c.recipient)} · ${esc(c.address1)}${c.address2?', '+esc(c.address2):''}<br>${esc(c.city)}, ${esc(c.state)} ${esc(c.postal)} · ${esc(c.country)}</div>${summaryHTML(r.quote.items)}<p class="receipt-contact">Artwork: ${r.filename?esc(r.filename)+(r.preview?' (preview only; not uploaded)':''):'To follow'}${c.deliveryDate?'<br>Requested delivery date: '+esc(c.deliveryDate):''}</p>${!r.preview&&!r.confirmationSent?'<p class="field-help">Your request reached our email service, but the confirmation email could not be confirmed. Keep this reference for your records.</p>':''}<p class="field-help">This is a request for pricing, not an accepted order.</p></div><div class="actions receipt-actions"><a class="button" href="${r.preview?'/quote/cart/':'/products/'}">${r.preview?'Back to your quote':'Explore more products'} ${icon('arrow-right')}</a><button type="button" class="text-button" id="print-receipt">Print / save summary</button></div>`;$('#print-receipt').addEventListener('click',()=>print());if(window.QXP_EMAIL){const customer=QXP_EMAIL.render(r.quote,r.reference,r.filename,true),team=QXP_EMAIL.render(r.quote,r.reference,r.filename,false);for(const [title,html] of [['Customer confirmation preview',customer.html],['Quixprint notification preview',team.html]]){const details=document.createElement('details');details.className='email-preview';const summary=document.createElement('summary');summary.textContent=title;const iframe=document.createElement('iframe');iframe.title=title;iframe.setAttribute('sandbox','');iframe.srcdoc=html;details.append(summary,iframe);root.append(details)}}}
function initHomeJournal(){const root=$('#home-journal');if(!root)return;const cards=$$('[data-journal-index]',root).sort((a,b)=>Number(a.dataset.journalIndex)-Number(b.dataset.journalIndex));if(!cards.length)return;const day=Math.floor(Date.now()/86400000),count=Math.min(3,cards.length),start=(day*3)%cards.length;cards.forEach(card=>card.hidden=true);for(let i=0;i<count;i++){const card=cards[(start+i)%cards.length];card.hidden=false;root.append(card);}}
let destroyHero=()=>{};
function initHero(){
 destroyHero();
 const gallery=$('#hero-gallery');if(!gallery)return;
 const slides=$$('[data-hero-slide]',gallery),pause=$('#hero-pause',gallery),description=$('#hero-image-description',gallery);
 const motion=matchMedia('(prefers-reduced-motion: reduce)'),events=new AbortController();
 let current=0,timer=null,paused=false,hovered=false,focused=false,inView=true,disposed=false,request=0;
 function schedule(){clearTimeout(timer);if(!disposed&&!paused&&!hovered&&!focused&&inView&&!motion.matches&&!document.hidden)timer=setTimeout(()=>{show((current+1)%slides.length);schedule();},4500);}
 function show(index){
  const serial=++request,img=slides[index];
  function apply(){if(disposed||serial!==request)return;current=index;slides.forEach((s,i)=>{s.classList.toggle('is-active',i===current);s.setAttribute('aria-hidden',String(i!==current));});description.textContent=img.alt;}
  if(img.complete){if(img.naturalWidth>0)apply();}else img.addEventListener('load',apply,{once:true,signal:events.signal});
 }
 function listen(el,type,fn){el.addEventListener(type,fn,{signal:events.signal});}
 listen(pause,'click',()=>{paused=!paused;pause.setAttribute('aria-label',paused?'Play image rotation':'Pause image rotation');schedule();});
 listen(gallery,'pointerenter',e=>{if(e.pointerType==='mouse'){hovered=true;schedule();}});
 listen(gallery,'pointerleave',()=>{hovered=false;schedule();});
 listen(gallery,'focusin',()=>{focused=true;schedule();});
 listen(gallery,'focusout',e=>{focused=gallery.contains(e.relatedTarget);schedule();});
 listen(document,'visibilitychange',schedule);
 function preference(){pause.disabled=motion.matches;schedule();}
 listen(motion,'change',preference);
 const observer=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{inView=entries[0].isIntersecting;schedule();},{threshold:0.1}):null;
 observer?.observe(gallery);
 destroyHero=()=>{disposed=true;clearTimeout(timer);events.abort();observer?.disconnect();};
 preference();
}
let lastJournalFeature=null;
function initJournal(){const features=$$('[data-journal-feature]');if(!features.length)return;let previous=lastJournalFeature;try{previous=sessionStorage.getItem('qxp.journal.feature')||previous}catch{}const candidates=features.filter(el=>el.getAttribute('href')!==previous),pool=candidates.length?candidates:features,chosen=pool[Math.floor(Math.random()*pool.length)];features.forEach(el=>el.hidden=el!==chosen);$$('[data-journal-archive]').forEach(el=>el.hidden=el.dataset.journalArchive===chosen.dataset.journalFeature);lastJournalFeature=chosen.getAttribute('href');try{sessionStorage.setItem('qxp.journal.feature',lastJournalFeature)}catch{}}
function initialize(){initHero();initHomeJournal();initJournal();updateCount();initCatalog();initProduct();initCart();initCheckout();initReceipt();}
function renderOffline(){const r=route(),page=window.QXP_PAGES[r.pathname]||window.QXP_PAGES['/404/'];if(!page)return;const old=$('main');const holder=document.createElement('div');holder.innerHTML=page.html;old.replaceWith(holder.firstElementChild);document.title=page.title;document.body.dataset.page=page.type;document.body.dataset.product=page.product||'';menu(false);window.QXP_HYDRATE?.(document);initialize();if(r.hash){const target=document.getElementById(r.hash.slice(1));target?.scrollIntoView()}else{scrollTo(0,0);$('#main').focus({preventScroll:true});}}
window.addEventListener('storage',e=>{if(e.key===STORE){updateCount();if($('#cart-items'))initCart();if($('#checkout-items'))$('#checkout-items').innerHTML=summaryHTML(cart());}});
bindHeader();bindUnwindGuide();function categoryAccessibility(){const mobile=innerWidth<=760;$$('.category-toggle').forEach(b=>{b.tabIndex=mobile?0:-1;b.setAttribute('aria-expanded',String(!mobile));$('#'+b.getAttribute('aria-controls')).classList.remove('open');$('span',b).innerHTML=icon('plus');});}categoryAccessibility();matchMedia('(max-width:760px)').addEventListener('change',categoryAccessibility);if(window.QXP_OFFLINE){window.addEventListener('hashchange',renderOffline);renderOffline()}else initialize();
})();
